-- Tabla artists (PostgreSQL)
-- List<String> -> text[]  | listeners -> double precision | country -> ISO-2
-- status: libre, pero dejamos un CHECK de ejemplo

CREATE SEQUENCE IF NOT EXISTS artists_id_seq;

CREATE TABLE IF NOT EXISTS artists (
    id         BIGINT PRIMARY KEY DEFAULT nextval('artists_id_seq'),
    name       VARCHAR(255) NOT NULL,
    genres     TEXT[]       NOT NULL DEFAULT '{}',
    country    VARCHAR(2)   NOT NULL,                 -- ES, US, GB, etc.
    listeners  INTEGER,                      -- oyentes mensuales
    status     VARCHAR(32)  NOT NULL DEFAULT 'Activo',
    biography  VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT artists_status_ck CHECK (status IN ('Activo','Borrador'))
);

-- Índices útiles
CREATE INDEX IF NOT EXISTS idx_artists_name ON artists (name);
CREATE INDEX IF NOT EXISTS idx_artists_country ON artists (country);
CREATE INDEX IF NOT EXISTS idx_artists_genres_gin ON artists USING GIN (genres);


ALTER SEQUENCE artists_id_seq OWNED BY artists.id;


INSERT INTO artists (name, genres, country, listeners, status) VALUES
   ('Taylor Swift', ARRAY['Pop','Country']::TEXT[], 'US', 115000000, 'Activo'),
   ('Ed Sheeran', ARRAY['Pop','Singer-Songwriter']::TEXT[], 'GB', 108000000, 'Activo'),
   ('Bad Bunny', ARRAY['Reggaeton','Latin']::TEXT[], 'PR', 103000000, 'Activo'),
   ('Drake', ARRAY['Hip Hop','Rap']::TEXT[], 'CA', 101000000, 'Activo'),
   ('The Weeknd', ARRAY['R&B','Pop']::TEXT[], 'CA', 110000000, 'Activo'),
   ('Billie Eilish', ARRAY['Pop','Alternative']::TEXT[], 'US', 88000000, 'Activo'),
   ('Dua Lipa', ARRAY['Pop']::TEXT[], 'GB', 84000000, 'Activo'),
   ('Adele', ARRAY['Pop','Soul']::TEXT[], 'GB', 87000000, 'Activo'),
   ('Beyoncé', ARRAY['Pop','R&B']::TEXT[], 'US', 92000000, 'Activo'),
   ('Rihanna', ARRAY['Pop','R&B']::TEXT[], 'BB', 90000000, 'Activo'),
   ('Bruno Mars', ARRAY['Pop','Funk']::TEXT[], 'US', 82000000, 'Activo'),
   ('Post Malone', ARRAY['Hip Hop','Pop']::TEXT[], 'US', 76000000, 'Activo'),
   ('Shakira', ARRAY['Pop','Latin']::TEXT[], 'CO', 72000000, 'Activo'),
   ('Karol G', ARRAY['Reggaeton','Latin']::TEXT[], 'CO', 70000000, 'Activo'),
   ('ROSALÍA', ARRAY['Flamenco','Pop','Alternative']::TEXT[], 'ES', 40000000, 'Activo'),
   ('C. Tangana', ARRAY['Rap','Pop','Latin']::TEXT[], 'ES', 12000000, 'Activo'),
   ('Quevedo', ARRAY['Reggaeton','Latin']::TEXT[], 'ES', 18000000, 'Activo'),
   ('Aitana', ARRAY['Pop']::TEXT[], 'ES', 14000000, 'Activo'),
   ('Lola Índigo', ARRAY['Pop','Latin']::TEXT[], 'ES', 9000000, 'Activo'),
   ('Manuel Turizo', ARRAY['Latin','Reggaeton']::TEXT[], 'CO', 26000000, 'Activo'),
   ('J Balvin', ARRAY['Reggaeton','Latin']::TEXT[], 'CO', 58000000, 'Activo'),
   ('Maluma', ARRAY['Reggaeton','Latin']::TEXT[], 'CO', 48000000, 'Activo'),
   ('Selena Gomez', ARRAY['Pop']::TEXT[], 'US', 74000000, 'Activo'),
   ('Olivia Rodrigo', ARRAY['Pop','Alt Pop']::TEXT[], 'US', 75000000, 'Activo'),
   ('BLACKPINK', ARRAY['K-Pop']::TEXT[], 'KR', 32000000, 'Activo'),
   ('BTS', ARRAY['K-Pop']::TEXT[], 'KR', 45000000, 'Activo'),
   ('NewJeans', ARRAY['K-Pop']::TEXT[], 'KR', 21000000, 'Activo'),
   ('Stray Kids', ARRAY['K-Pop']::TEXT[], 'KR', 19000000, 'Activo'),
   ('Metallica', ARRAY['Metal','Hard Rock']::TEXT[], 'US', 32000000, 'Activo'),
   ('Arctic Monkeys', ARRAY['Indie Rock','Alternative']::TEXT[], 'GB', 45000000, 'Activo'),
   ('Imagine Dragons', ARRAY['Alternative','Pop Rock']::TEXT[], 'US', 65000000, 'Activo'),
   ('Eminem', ARRAY['Hip Hop','Rap']::TEXT[], 'US', 77000000, 'Activo'),
   ('Coldplay', ARRAY['Alternative','Pop Rock']::TEXT[], 'GB', 98000000, 'Activo'),
   ('Red Hot Chili Peppers', ARRAY['Funk Rock','Alternative']::TEXT[], 'US', 30000000, 'Activo'),
   ('Foo Fighters', ARRAY['Rock','Alternative']::TEXT[], 'US', 27000000, 'Activo'),
   ('Nirvana', ARRAY['Grunge','Alternative']::TEXT[], 'US', 34000000, 'Activo'),
   ('Radiohead', ARRAY['Alternative','Art Rock']::TEXT[], 'GB', 22000000, 'Activo'),
   ('Muse', ARRAY['Alternative','Prog Rock']::TEXT[], 'GB', 19000000, 'Activo'),
   ('Tame Impala', ARRAY['Psychedelic','Alternative']::TEXT[], 'AU', 16000000, 'Activo'),
   ('Portishead', ARRAY['Trip Hop']::TEXT[], 'GB', 4000000, 'Activo'),
   ('Massive Attack', ARRAY['Trip Hop']::TEXT[], 'GB', 8000000, 'Activo'),
   ('The Chemical Brothers', ARRAY['Electronic','Big Beat']::TEXT[], 'GB', 7000000, 'Activo'),
   ('Calvin Harris', ARRAY['EDM','House']::TEXT[], 'GB', 52000000, 'Activo'),
   ('David Guetta', ARRAY['EDM','House']::TEXT[], 'FR', 70000000, 'Activo'),
   ('Avicii', ARRAY['EDM','Progressive House']::TEXT[], 'SE', 38000000, 'Activo'),
   ('Martin Garrix', ARRAY['EDM','Progressive House']::TEXT[], 'NL', 40000000, 'Activo'),
   ('Tiesto', ARRAY['EDM','Trance']::TEXT[], 'NL', 30000000, 'Activo'),
   ('Skrillex', ARRAY['Dubstep','EDM']::TEXT[], 'US', 22000000, 'Activo'),
   ('Deadmau5', ARRAY['Progressive House']::TEXT[], 'CA', 8000000, 'Activo'),
   ('Swedish House Mafia', ARRAY['EDM']::TEXT[], 'SE', 9000000, 'Activo'),
   ('Armin van Buuren', ARRAY['Trance']::TEXT[], 'NL', 12000000, 'Activo'),
   ('Paul Kalkbrenner', ARRAY['Techno']::TEXT[], 'DE', 3000000, 'Activo'),
   ('Nina Kraviz', ARRAY['Techno']::TEXT[], 'RU', 2000000, 'Activo'),
   ('Ben Böhmer', ARRAY['Melodic House','Techno']::TEXT[], 'DE', 3000000, 'Activo'),
   ('Sonny Fodera', ARRAY['House']::TEXT[], 'AU', 5000000, 'Activo'),
   ('Disclosure', ARRAY['House','Garage']::TEXT[], 'GB', 10000000, 'Activo'),
   ('Gorillaz', ARRAY['Alternative','Electronic']::TEXT[], 'GB', 19000000, 'Activo'),
   ('Daft Punk', ARRAY['Electronic','House']::TEXT[], 'FR', 24000000, 'Activo'),
   ('Justice', ARRAY['Electronic']::TEXT[], 'FR', 4000000, 'Activo'),
   ('Kendrick Lamar', ARRAY['Hip Hop','Rap']::TEXT[], 'US', 43000000, 'Activo'),
   ('Travis Scott', ARRAY['Hip Hop']::TEXT[], 'US', 55000000, 'Activo'),
   ('Doja Cat', ARRAY['Pop','Rap']::TEXT[], 'US', 67000000, 'Activo'),
   ('Nicki Minaj', ARRAY['Rap','Pop']::TEXT[], 'TT', 65000000, 'Activo'),
   ('Anitta', ARRAY['Funk Carioca','Pop']::TEXT[], 'BR', 23000000, 'Activo'),
   ('Pabllo Vittar', ARRAY['Pop']::TEXT[], 'BR', 9000000, 'Activo'),
   ('Jorge Drexler', ARRAY['Singer-Songwriter','Latin']::TEXT[], 'UY', 3000000, 'Activo'),
   ('Luis Fonsi', ARRAY['Latin Pop']::TEXT[], 'PR', 20000000, 'Activo'),
   ('Daddy Yankee', ARRAY['Reggaeton']::TEXT[], 'PR', 34000000, 'Activo'),
   ('Enrique Iglesias', ARRAY['Pop','Latin']::TEXT[], 'ES', 18000000, 'Activo'),
   ('Pablo Alborán', ARRAY['Pop']::TEXT[], 'ES', 7000000, 'Activo'),
   ('Alejandro Sanz', ARRAY['Pop']::TEXT[], 'ES', 6000000, 'Activo'),
   ('Melendi', ARRAY['Pop','Rumba']::TEXT[], 'ES', 5000000, 'Activo'),
   ('Maná', ARRAY['Rock','Latin']::TEXT[], 'MX', 8000000, 'Activo'),
   ('Café Tacuba', ARRAY['Rock','Alternative']::TEXT[], 'MX', 4000000, 'Activo'),
   ('Zoé', ARRAY['Alternative','Rock']::TEXT[], 'MX', 3000000, 'Activo'),
   ('Molotov', ARRAY['Rock','Rap']::TEXT[], 'MX', 3500000, 'Activo'),
   ('Juanes', ARRAY['Rock','Latin']::TEXT[], 'CO', 10000000, 'Activo'),
   ('Manolo García', ARRAY['Pop','Rock']::TEXT[], 'ES', 2000000, 'Activo'),
   ('Extremoduro', ARRAY['Rock']::TEXT[], 'ES', 1500000, 'Activo'),
   ('Fito & Fitipaldis', ARRAY['Rock']::TEXT[], 'ES', 2500000, 'Activo'),
   ('Vetusta Morla', ARRAY['Indie Rock']::TEXT[], 'ES', 3000000, 'Activo'),
   ('Love of Lesbian', ARRAY['Indie Pop']::TEXT[], 'ES', 2000000, 'Activo'),
   ('Izal', ARRAY['Indie Pop']::TEXT[], 'ES', 1800000, 'Activo'),
   ('M-Clan', ARRAY['Rock']::TEXT[], 'ES', 1200000, 'Activo'),
   ('La Oreja de Van Gogh', ARRAY['Pop']::TEXT[], 'ES', 4000000, 'Activo'),
   ('Amaral', ARRAY['Pop','Rock']::TEXT[], 'ES', 5000000, 'Activo'),
   ('Héroes del Silencio', ARRAY['Rock']::TEXT[], 'ES', 6000000, 'Activo'),
   ('Mecano', ARRAY['Pop']::TEXT[], 'ES', 7000000, 'Activo'),
   ('Raphael', ARRAY['Balada','Pop']::TEXT[], 'ES', 500000, 'Activo'),
   ('Julio Iglesias', ARRAY['Pop']::TEXT[], 'ES', 8000000, 'Activo'),
   ('Camila Cabello', ARRAY['Pop']::TEXT[], 'US', 60000000, 'Activo'),
   ('Shawn Mendes', ARRAY['Pop']::TEXT[], 'CA', 55000000, 'Activo'),
   ('Justin Bieber', ARRAY['Pop']::TEXT[], 'CA', 98000000, 'Activo'),
   ('Harry Styles', ARRAY['Pop','Rock']::TEXT[], 'GB', 72000000, 'Activo'),
   ('Zayn', ARRAY['Pop','R&B']::TEXT[], 'GB', 15000000, 'Activo'),
   ('Niall Horan', ARRAY['Pop']::TEXT[], 'IE', 12000000, 'Activo'),
   ('Liam Payne', ARRAY['Pop']::TEXT[], 'GB', 8000000, 'Activo'),
   ('Louis Tomlinson', ARRAY['Pop']::TEXT[], 'GB', 7000000, 'Activo'),
   ('OneRepublic', ARRAY['Pop Rock']::TEXT[], 'US', 25000000, 'Activo'),
   ('Maroon 5', ARRAY['Pop Rock']::TEXT[], 'US', 78000000, 'Activo');