-- Tabla artists (PostgreSQL)
-- List<String> -> text[]  | listeners -> double precision | country -> ISO-2
-- status: libre, pero dejamos un CHECK de ejemplo

CREATE TABLE IF NOT EXISTS artists (
    id         BIGINT PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    genres     TEXT[]       NOT NULL DEFAULT '{}',
    country    VARCHAR(2)   NOT NULL,                 -- ES, US, GB, etc.
    listeners  DOUBLE PRECISION,                      -- oyentes mensuales
    status     VARCHAR(32)  NOT NULL DEFAULT 'Activo',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT artists_status_ck CHECK (status IN ('Activo','Borrador'))
);

-- Índices útiles
CREATE INDEX IF NOT EXISTS idx_artists_name ON artists (name);
CREATE INDEX IF NOT EXISTS idx_artists_country ON artists (country);
CREATE INDEX IF NOT EXISTS idx_artists_genres_gin ON artists USING GIN (genres);


INSERT INTO artists (id, name, genres, country, listeners, status) VALUES
                                                                       (1, 'Taylor Swift', ARRAY['Pop','Country']::TEXT[], 'US', 115000000, 'Activo'),
                                                                       (2, 'Ed Sheeran', ARRAY['Pop','Singer-Songwriter']::TEXT[], 'GB', 108000000, 'Activo'),
                                                                       (3, 'Bad Bunny', ARRAY['Reggaeton','Latin']::TEXT[], 'PR', 103000000, 'Activo'),
                                                                       (4, 'Drake', ARRAY['Hip Hop','Rap']::TEXT[], 'CA', 101000000, 'Activo'),
                                                                       (5, 'The Weeknd', ARRAY['R&B','Pop']::TEXT[], 'CA', 110000000, 'Activo'),
                                                                       (6, 'Billie Eilish', ARRAY['Pop','Alternative']::TEXT[], 'US', 88000000, 'Activo'),
                                                                       (7, 'Dua Lipa', ARRAY['Pop']::TEXT[], 'GB', 84000000, 'Activo'),
                                                                       (8, 'Adele', ARRAY['Pop','Soul']::TEXT[], 'GB', 87000000, 'Activo'),
                                                                       (9, 'Beyoncé', ARRAY['Pop','R&B']::TEXT[], 'US', 92000000, 'Activo'),
                                                                       (10, 'Rihanna', ARRAY['Pop','R&B']::TEXT[], 'BB', 90000000, 'Activo'),
                                                                       (11, 'Bruno Mars', ARRAY['Pop','Funk']::TEXT[], 'US', 82000000, 'Activo'),
                                                                       (12, 'Post Malone', ARRAY['Hip Hop','Pop']::TEXT[], 'US', 76000000, 'Activo'),
                                                                       (13, 'Shakira', ARRAY['Pop','Latin']::TEXT[], 'CO', 72000000, 'Activo'),
                                                                       (14, 'Karol G', ARRAY['Reggaeton','Latin']::TEXT[], 'CO', 70000000, 'Activo'),
                                                                       (15, 'ROSALÍA', ARRAY['Flamenco','Pop','Alternative']::TEXT[], 'ES', 40000000, 'Activo'),
                                                                       (16, 'C. Tangana', ARRAY['Rap','Pop','Latin']::TEXT[], 'ES', 12000000, 'Activo'),
                                                                       (17, 'Quevedo', ARRAY['Reggaeton','Latin']::TEXT[], 'ES', 18000000, 'Activo'),
                                                                       (18, 'Aitana', ARRAY['Pop']::TEXT[], 'ES', 14000000, 'Activo'),
                                                                       (19, 'Lola Índigo', ARRAY['Pop','Latin']::TEXT[], 'ES', 9000000, 'Activo'),
                                                                       (20, 'Manuel Turizo', ARRAY['Latin','Reggaeton']::TEXT[], 'CO', 26000000, 'Activo'),
                                                                       (21, 'J Balvin', ARRAY['Reggaeton','Latin']::TEXT[], 'CO', 58000000, 'Activo'),
                                                                       (22, 'Maluma', ARRAY['Reggaeton','Latin']::TEXT[], 'CO', 48000000, 'Activo'),
                                                                       (23, 'Selena Gomez', ARRAY['Pop']::TEXT[], 'US', 74000000, 'Activo'),
                                                                       (24, 'Olivia Rodrigo', ARRAY['Pop','Alt Pop']::TEXT[], 'US', 75000000, 'Activo'),
                                                                       (25, 'BLACKPINK', ARRAY['K-Pop']::TEXT[], 'KR', 32000000, 'Activo'),
                                                                       (26, 'BTS', ARRAY['K-Pop']::TEXT[], 'KR', 45000000, 'Activo'),
                                                                       (27, 'NewJeans', ARRAY['K-Pop']::TEXT[], 'KR', 21000000, 'Activo'),
                                                                       (28, 'Stray Kids', ARRAY['K-Pop']::TEXT[], 'KR', 19000000, 'Activo'),
                                                                       (29, 'Metallica', ARRAY['Metal','Hard Rock']::TEXT[], 'US', 32000000, 'Activo'),
                                                                       (30, 'Arctic Monkeys', ARRAY['Indie Rock','Alternative']::TEXT[], 'GB', 45000000, 'Activo'),
                                                                       (31, 'Imagine Dragons', ARRAY['Alternative','Pop Rock']::TEXT[], 'US', 65000000, 'Activo'),
                                                                       (32, 'Eminem', ARRAY['Hip Hop','Rap']::TEXT[], 'US', 77000000, 'Activo'),
                                                                       (33, 'Coldplay', ARRAY['Alternative','Pop Rock']::TEXT[], 'GB', 98000000, 'Activo'),
                                                                       (34, 'Red Hot Chili Peppers', ARRAY['Funk Rock','Alternative']::TEXT[], 'US', 30000000, 'Activo'),
                                                                       (35, 'Foo Fighters', ARRAY['Rock','Alternative']::TEXT[], 'US', 27000000, 'Activo'),
                                                                       (36, 'Nirvana', ARRAY['Grunge','Alternative']::TEXT[], 'US', 34000000, 'Activo'),
                                                                       (37, 'Radiohead', ARRAY['Alternative','Art Rock']::TEXT[], 'GB', 22000000, 'Activo'),
                                                                       (38, 'Muse', ARRAY['Alternative','Prog Rock']::TEXT[], 'GB', 19000000, 'Activo'),
                                                                       (39, 'Tame Impala', ARRAY['Psychedelic','Alternative']::TEXT[], 'AU', 16000000, 'Activo'),
                                                                       (40, 'Portishead', ARRAY['Trip Hop']::TEXT[], 'GB', 4000000, 'Activo'),
                                                                       (41, 'Massive Attack', ARRAY['Trip Hop']::TEXT[], 'GB', 8000000, 'Activo'),
                                                                       (42, 'The Chemical Brothers', ARRAY['Electronic','Big Beat']::TEXT[], 'GB', 7000000, 'Activo'),
                                                                       (43, 'Calvin Harris', ARRAY['EDM','House']::TEXT[], 'GB', 52000000, 'Activo'),
                                                                       (44, 'David Guetta', ARRAY['EDM','House']::TEXT[], 'FR', 70000000, 'Activo'),
                                                                       (45, 'Avicii', ARRAY['EDM','Progressive House']::TEXT[], 'SE', 38000000, 'Activo'),
                                                                       (46, 'Martin Garrix', ARRAY['EDM','Progressive House']::TEXT[], 'NL', 40000000, 'Activo'),
                                                                       (47, 'Tiesto', ARRAY['EDM','Trance']::TEXT[], 'NL', 30000000, 'Activo'),
                                                                       (48, 'Skrillex', ARRAY['Dubstep','EDM']::TEXT[], 'US', 22000000, 'Activo'),
                                                                       (49, 'Deadmau5', ARRAY['Progressive House']::TEXT[], 'CA', 8000000, 'Activo'),
                                                                       (50, 'Swedish House Mafia', ARRAY['EDM']::TEXT[], 'SE', 9000000, 'Activo'),
                                                                       (51, 'Armin van Buuren', ARRAY['Trance']::TEXT[], 'NL', 12000000, 'Activo'),
                                                                       (52, 'Paul Kalkbrenner', ARRAY['Techno']::TEXT[], 'DE', 3000000, 'Activo'),
                                                                       (53, 'Nina Kraviz', ARRAY['Techno']::TEXT[], 'RU', 2000000, 'Activo'),
                                                                       (54, 'Ben Böhmer', ARRAY['Melodic House','Techno']::TEXT[], 'DE', 3000000, 'Activo'),
                                                                       (55, 'Sonny Fodera', ARRAY['House']::TEXT[], 'AU', 5000000, 'Activo'),
                                                                       (56, 'Disclosure', ARRAY['House','Garage']::TEXT[], 'GB', 10000000, 'Activo'),
                                                                       (57, 'Gorillaz', ARRAY['Alternative','Electronic']::TEXT[], 'GB', 19000000, 'Activo'),
                                                                       (58, 'Daft Punk', ARRAY['Electronic','House']::TEXT[], 'FR', 24000000, 'Activo'),
                                                                       (59, 'Justice', ARRAY['Electronic']::TEXT[], 'FR', 4000000, 'Activo'),
                                                                       (60, 'Kendrick Lamar', ARRAY['Hip Hop','Rap']::TEXT[], 'US', 43000000, 'Activo'),
                                                                       (61, 'Travis Scott', ARRAY['Hip Hop']::TEXT[], 'US', 55000000, 'Activo'),
                                                                       (62, 'Doja Cat', ARRAY['Pop','Rap']::TEXT[], 'US', 67000000, 'Activo'),
                                                                       (63, 'Nicki Minaj', ARRAY['Rap','Pop']::TEXT[], 'TT', 65000000, 'Activo'),
                                                                       (64, 'Anitta', ARRAY['Funk Carioca','Pop']::TEXT[], 'BR', 23000000, 'Activo'),
                                                                       (65, 'Pabllo Vittar', ARRAY['Pop']::TEXT[], 'BR', 9000000, 'Activo'),
                                                                       (66, 'Jorge Drexler', ARRAY['Singer-Songwriter','Latin']::TEXT[], 'UY', 3000000, 'Activo'),
                                                                       (67, 'Luis Fonsi', ARRAY['Latin Pop']::TEXT[], 'PR', 20000000, 'Activo'),
                                                                       (68, 'Daddy Yankee', ARRAY['Reggaeton']::TEXT[], 'PR', 34000000, 'Activo'),
                                                                       (69, 'Enrique Iglesias', ARRAY['Pop','Latin']::TEXT[], 'ES', 18000000, 'Activo'),
                                                                       (70, 'Pablo Alborán', ARRAY['Pop']::TEXT[], 'ES', 7000000, 'Activo'),
                                                                       (71, 'Alejandro Sanz', ARRAY['Pop']::TEXT[], 'ES', 6000000, 'Activo'),
                                                                       (72, 'Melendi', ARRAY['Pop','Rumba']::TEXT[], 'ES', 5000000, 'Activo'),
                                                                       (73, 'Maná', ARRAY['Rock','Latin']::TEXT[], 'MX', 8000000, 'Activo'),
                                                                       (74, 'Café Tacuba', ARRAY['Rock','Alternative']::TEXT[], 'MX', 4000000, 'Activo'),
                                                                       (75, 'Zoé', ARRAY['Alternative','Rock']::TEXT[], 'MX', 3000000, 'Activo'),
                                                                       (76, 'Molotov', ARRAY['Rock','Rap']::TEXT[], 'MX', 3500000, 'Activo'),
                                                                       (77, 'Juanes', ARRAY['Rock','Latin']::TEXT[], 'CO', 10000000, 'Activo'),
                                                                       (78, 'Manolo García', ARRAY['Pop','Rock']::TEXT[], 'ES', 2000000, 'Activo'),
                                                                       (79, 'Extremoduro', ARRAY['Rock']::TEXT[], 'ES', 1500000, 'Activo'),
                                                                       (80, 'Fito & Fitipaldis', ARRAY['Rock']::TEXT[], 'ES', 2500000, 'Activo'),
                                                                       (81, 'Vetusta Morla', ARRAY['Indie Rock']::TEXT[], 'ES', 3000000, 'Activo'),
                                                                       (82, 'Love of Lesbian', ARRAY['Indie Pop']::TEXT[], 'ES', 2000000, 'Activo'),
                                                                       (83, 'Izal', ARRAY['Indie Pop']::TEXT[], 'ES', 1800000, 'Activo'),
                                                                       (84, 'M-Clan', ARRAY['Rock']::TEXT[], 'ES', 1200000, 'Activo'),
                                                                       (85, 'La Oreja de Van Gogh', ARRAY['Pop']::TEXT[], 'ES', 4000000, 'Activo'),
                                                                       (86, 'Amaral', ARRAY['Pop','Rock']::TEXT[], 'ES', 5000000, 'Activo'),
                                                                       (87, 'Héroes del Silencio', ARRAY['Rock']::TEXT[], 'ES', 6000000, 'Activo'),
                                                                       (88, 'Mecano', ARRAY['Pop']::TEXT[], 'ES', 7000000, 'Activo'),
                                                                       (89, 'Raphael', ARRAY['Balada','Pop']::TEXT[], 'ES', 500000, 'Activo'),
                                                                       (90, 'Julio Iglesias', ARRAY['Pop']::TEXT[], 'ES', 8000000, 'Activo'),
                                                                       (91, 'Camila Cabello', ARRAY['Pop']::TEXT[], 'US', 60000000, 'Activo'),
                                                                       (92, 'Shawn Mendes', ARRAY['Pop']::TEXT[], 'CA', 55000000, 'Activo'),
                                                                       (93, 'Justin Bieber', ARRAY['Pop']::TEXT[], 'CA', 98000000, 'Activo'),
                                                                       (94, 'Harry Styles', ARRAY['Pop','Rock']::TEXT[], 'GB', 72000000, 'Activo'),
                                                                       (95, 'Zayn', ARRAY['Pop','R&B']::TEXT[], 'GB', 15000000, 'Activo'),
                                                                       (96, 'Niall Horan', ARRAY['Pop']::TEXT[], 'IE', 12000000, 'Activo'),
                                                                       (97, 'Liam Payne', ARRAY['Pop']::TEXT[], 'GB', 8000000, 'Activo'),
                                                                       (98, 'Louis Tomlinson', ARRAY['Pop']::TEXT[], 'GB', 7000000, 'Activo'),
                                                                       (99, 'OneRepublic', ARRAY['Pop Rock']::TEXT[], 'US', 25000000, 'Activo'),
                                                                       (100, 'Maroon 5', ARRAY['Pop Rock']::TEXT[], 'US', 78000000, 'Activo');